#default: 
# restore --> build --> test --> pack
#For update master || development
# + nuget-publish (-beta for development)
#If wip/**
# do nothing
# Only projects 
name: build

on:
  push:
    branches-ignore: ["wip/**"]

env:
  SLN: src/Repository.csproj

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Build and test"
    steps:
    - uses: actions/checkout@v3
  
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x

    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    
    - name: Restore dependencies
      run: dotnet restore --locked-mode $SLN

    - name: Build
      run: dotnet build --no-restore -c Release $SLN -p:ContinuousIntegrationBuild=true

    - name: Test
      run: >
        dotnet test 
        --no-build 
        -c Release 
        --verbosity normal 
        --logger trx 
        --results-directory "TestResults" 
        --filter TestCategory\!=Integration
        $SLN
    
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: TestResults
      if: ${{ always() }}

    - name: Pack
      run: dotnet publish --no-build -c Release -o ./bin/Main $SLN
      if: success() && github.ref != 'refs/heads/development'

    - name: Keep package artifact
      uses: actions/upload-artifact@v3
      with:
        name: package
        path: bin/**/*
        if-no-files-found: error
   